{% set name = "sekve" %}
{% set version = "1.0.5" %}


package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e4906c5a1782fb3afe2008263e48474339a4a06fe1a38d4fc42166c2131d8ac


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - sekve

about:
  home: https://gitlab.com/moscm/sekv-e
  summary: SEKV-E is a Python-based parameters extractor for the simplified EKV model.
  description: SEKV-E is a Python-based parameters extractor for the simplified EKV model, which is developed by ICLAB, EPFL. While it has been developed to serve the needs of low-power analog circuit designs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://people.epfl.ch/hung.han

extra:
  recipe-maintainers:
    - vicentetm
    - hung-chi
