{% set name = "sekve" %}
{% set version = "1.0.3" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8b7d426adc63bb0b0830b6c8e3ecc7029d49d30e6c73a67da784802956b2961

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - matplotlib-base =3.5.1
    - numpy =1.22.3
    - pandas =1.4.2
    - scipy =1.7.3

test:
  imports:
    - sekve

about:
  home: https://gitlab.com/moscm/sekv-e
  summary: SEKV-E is a Python-based parameters extractor for the simplified EKV model.
  description: SEKV-E is a Python-based parameters extractor for the simplified EKV model, which is developed by ICLAB, EPFL. While it has been developed to serve the needs of low-power analog circuit designs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://people.epfl.ch/hung.han

extra:
  recipe-maintainers:
    - vicentetm
    - hung-chi
